add exception
java-park-mail-ru/CaesarTeam-09-2017 pull request #1
Opened 2017-09-17 23:13 UTC by sevaTechoPark

Не знаю пока как обработать JSON Parse exception

2017-09-18 08:08 UTC, Badya commented on pom.xml
> +    <artifactId>homework1</artifactId>
"В файле pom.xml, в названии проекта, должно стоять имя именно вашего проекта"
`groupId` используйте название команды, `artifactId` соответственно название игры

2017-09-18 08:35 UTC, Badya commented on src/main/java/server/controllers/MainController.java
> +    private HashMap<String, String>  users;
Дабы избавиться от нагромождения HasMap'ов рекомендую подумать в сторону выделения пользователя в отдельную сущность, при этом важно не забыть про методы класса Object (вопрос будет в РК).

2017-09-18 08:35 UTC, Badya commented on src/main/java/server/controllers/MainController.java
> +    private HashMap<String, Integer> usersSession;
Для хранения рекомендуется завести отдельную сущность которая будет реализовывать некий интерфейс - в последствии реализация будет заменена на работу с базой практически безболезненно.

2017-09-18 08:35 UTC, Badya commented on src/main/java/server/controllers/MainController.java
> +    private HashMap<String, String>  users;
Правильной практикой будет объявлять в типах не конкретную реализацию а интерфейс:
`private Map<String, String> myMap = new HashMap<>();`

2017-09-18 08:35 UTC, Badya commented on src/main/java/server/controllers/MainController.java
> +        LinkedHashMap<String, String> map = new LinkedHashMap<>();
Про интерфейс и реализацию см. выше.
Данная мапина имеет совсем не говорящее название - рекомендуется переименовать в response хотя бы

2017-09-18 08:35 UTC, Badya commented on src/main/java/server/controllers/MainController.java
> +//            Находим пользователя по sessionId
В книгах вроде Effective Java и Clean Code описывается общий принцип: "Если коду требуется комментарий - значит этот код надо написать более понятным образом" (отрефакторить - выделить отдельные функции или сущности).
В общем случае комментов в вашем коде быть не должно, за исключением совсем узких мест.

2017-09-18 08:39 UTC, KSolovyev commented
в тревисе ошибка
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project homework1: Failed during checkstyle execution: Unable to find configuration file at location: park_checks.xml: Could not find resource 'park_checks.xml'. -> [Help 1]
файлик нужно положить в корень

2017-09-18 19:02 UTC, sevaTechoPark commented on src/main/java/server/controllers/MainController.java
> +    private HashMap<String, String>  users;
Почему выделить память лучше в месте объявления, а не в конструкторе, как было в С++ ?

2017-09-18 19:38 UTC, Badya commented on src/main/java/server/controllers/MainController.java
> +    private HashMap<String, String>  users;
Все, что можно инициализировать в филде - проще инициализировать там - конструктор же используется для параметризованных вещей, по факту поля объекта будут инициализированы(память выделена) перед вызовом конструктора.

2017-09-19 07:13 UTC, KSolovyev requested changes

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/controllers/AccountService.java
> +            httpSession.setAttribute("sessionId", id);
а зачем нужен sessionId? У сессии и так есть id. Можно получить его через httpSession.getSessionId()

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/controllers/AccountService.java
> +            response.put("registration", "ERROR");
вот этот вот параметр лишний. Вы и так кодом ответа все говорите

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/controllers/AccountService.java
> +            return ResponseEntity.ok(response);  // http response code 200
вот тут можно отвечать самой моделькой пользователя `ResponseEntity.ok(userProfile)`

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/JsonParser.java
> +public class JsonParser {
давайте назавем по-другому. JsonParser - сразу думаешь, что там внутри есть итерация по строке , анализ и парсинг текстовых данных. У вас же просто моделька. Давайте назовем это User и будем дальше везде использовать как модель пользователя, ага?

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/JsonParser.java
> +    @SuppressWarnings("unused")
давайте на класс перевесим Suppress

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/UsersProfile.java
> +    @SuppressWarnings("unused")
это сервис, здесь не должно быть неиспользуемых методов

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/controllers/AccountService.java
> +    @RequestMapping(method = RequestMethod.POST, path = "registr")
"registr" -  typo

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/UsersProfile.java
> +public class UsersProfile {
неудачное имя. Это у вас скорее UserService

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/controllers/AccountService.java
> +            password = "Uncorrect format. Use this format for password: \"password\":\"yourPassword\"";
typo: "Incorrect"

2017-09-19 07:13 UTC, KSolovyev commented on src/main/java/server/UsersProfile.java
> +    public void getAllUsers(Map<String, String> response) {
плохой дизайн метода. Сделайте 
```public List<User> getAllUsers() {...}```

2017-09-19 16:50 UTC, KSolovyev requested changes

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/UserService.java
> +    public boolean validation(String email, String username, String password, Map<String, String> response) {
Вот сюда, наверное, все-таки пользователя стоит передавать. Я посмотрел, вроде, во всех местах, где используется, есть пользователь

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +        list.forEach((value) -> {
здесь можно делать ResponseEntity.ok(list)

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +        } else {
else не нужен

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +            response.put("Cause", " \"" + username + "\" not registrated :( "
typo: "is not registered"

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +                    + "register: {\"email\",\"username\",\"password\"} on POST localhost:8081/registr");
Не надо пользователю говорить, какую ручку должен дернуть фронт, чтобы его зарегистрировать. Первого вполне достаточно

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +        } else if (!password.equals(userService.getPassword(username))) {
давайте без else - просто if

2017-09-19 16:50 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
лучше 403 отдавать

2017-09-20 11:16 UTC, KSolovyev requested changes

2017-09-20 11:16 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +            return ResponseEntity.status(HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE).body(response); // 416
а зачем так делать? Отдавайте просто пустой массив

2017-09-20 11:16 UTC, KSolovyev commented on src/main/java/server/User.java
> +        // зашифровать пароль здесь и записать в this.password
сделайте TODO
`//TODO: зашифровать пароль здесь и записать в this.password`

2017-09-20 19:13 UTC, Badya commented on src/main/java/server/controllers/AccountController.java
> +        Map<String, String> bodyResponse = new LinkedHashMap<>();
Зачем хешмап если можно объект?

2017-09-20 19:14 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
>      public ResponseEntity register(@RequestBody User user) { // как поймать исключения в конструкторе?
ловить не надо. Если будет исключение в конструкторе, пользователю вернется 400

2017-09-20 19:15 UTC, Badya commented on src/main/java/server/controllers/AccountController.java
> +        if (httpSession.getAttribute("username") == null) {
Вот такие строка как "username" обычно выделяют в более осмысленную константу для последующего переиспользования

2017-09-20 19:15 UTC, KSolovyev requested changes

2017-09-20 19:15 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +            return ResponseEntity.status(HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE).body(list); // 416
я имел в виду верните 200 OK и пустой список

2017-09-20 19:18 UTC, Badya commented on src/main/java/server/UserService.java
> +        if (password == null) {
А если пользователь допустил несколько ошибок при вводе данных - может упаковать все в один ответ - некий результат валидации

2017-09-20 19:21 UTC, Badya commented on src/main/java/server/controllers/AccountController.java
> +            userService.removeUser(oldUsername);
Напрашивается в UserService метод `rename`

2017-09-21 10:00 UTC, KSolovyev requested changes

2017-09-21 10:00 UTC, KSolovyev commented on src/main/java/server/controllers/AccountController.java
> +    private final String urlFrontendServer = "http://tp-2017-2-caesar.herokuapp.com";
`private static final String FRONTEND_ORIGIN="http://tp-2017-2-caesar.herokuapp.com";`

2017-09-21 10:01 UTC, KSolovyev requested changes

2017-09-21 10:01 UTC, KSolovyev commented on src/main/resources/application.properties
> +server.port=8081
зачем это?

2017-09-21 10:01 UTC, KSolovyev commented
правьте и будем мержить

2017-09-21 10:25 UTC, sevaTechoPark commented on src/main/resources/application.properties
> +server.port=8081
потому что,  сервер фронта по умолчанию тоже на 8080 запускается

2017-09-21 11:19 UTC, KSolovyev approved these changes

2017-09-21 11:35 UTC, merged

2017-09-21 11:36 UTC, KSolovyev commented
надо будет поребейзить девелоп на мастер и сделать форс пуш в девелоп