test and db done
java-park-mail-ru/CaesarTeam-09-2017 pull request #4
Opened 2017-10-17 18:58 UTC by sevaTechoPark

2017-10-17 21:01 UTC, sevaTechoPark commented
+ автодеплой на heroku
+ автоматический запуск тестов на travis по коммиту в репозиторий

2017-10-19 10:41 UTC, Badya requested changes
1) Разделите логику работы с базой от HTTP - не стоит мешать все в кучу - пускай база возвращает сущность, а контроллер работая с сущностью делает HTTP
2) хорошенько надо отрефакторить тесты сейчас там очень много копипасты которую можно сделать более читаемой

2017-10-19 10:41 UTC, Badya commented on src/main/java/server/account/AccountService.java
> +            final String sql = "SELECT * FROM FUser "
Очень странная штука - и вроде понятно зачем, но зачем?)

2017-10-19 10:41 UTC, Badya commented on src/main/java/server/account/AccountService.java
> +            return new ResponseEntity(account, HttpStatus.CREATED); // 201
Вообще плохая идея совмещать работу с базой и одновременно формирование неких HTTP ответов

2017-10-19 10:41 UTC, Badya commented on src/main/java/server/account/AccountService.java
> +        } catch (DuplicateKeyException e) {
Все исключения стоит логгировать.

2017-10-19 10:41 UTC, Badya commented on src/main/java/service/ServiceService.java
> +public class ServiceService {
Вам не показалось это странным?

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +//@Transactional
что за коммент?

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +	private MockMvc mockMvc;
почему это поехало?

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +                .andExpect(status().isCreated());
проверки в Before это не хорошая практика

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +    @Before
Вообще порядок вызова @Before  в одном классе не гарантирован

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +        mockMvc.perform(post("/api/auth/signup")
тут напрашиваются приватные методы чтобы этот тест стал более читаем

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +// *************************************** ME START***************************************
кресты какие-то - зачем?)

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +    public String getRandomString(SecureRandom random, int length){
зачем это паблик в тесте?

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +package server.account.AccountControllerTest;
файл на 374 строк даже гитхаб автоматически не грузит - что определенный намек на необходимость изменений)

2017-10-19 10:41 UTC, Badya commented on src/test/java/server/account/AccountServiceTest/AccountServiceTest.java
> +                getRandomString(SECURE_RANDOM, 10), getRandomString(SECURE_RANDOM, 10)));
Этот метод был найден в другом тестовом классе - напишите себе TestUtils

2017-10-19 13:19 UTC, sevaTechoPark commented on src/test/java/server/account/AccountServiceTest/AccountServiceTest.java
> +                getRandomString(SECURE_RANDOM, 10), getRandomString(SECURE_RANDOM, 10)));
сделал для getRandomString. Вы же это имели в виду?

2017-10-19 13:19 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +    public String getRandomString(SecureRandom random, int length){
перенес в утилс. сделал статиком

2017-10-19 13:21 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +// *************************************** ME START***************************************
что такое кресты? все подобные комменты убрал

2017-10-19 13:24 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +                .andExpect(status().isCreated());
убрал andExpect

2017-10-19 13:25 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +    @Before
слепил из двух before один

2017-10-19 13:25 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +//@Transactional
остался от Ивана Сопова. убрал

2017-10-19 13:28 UTC, sevaTechoPark commented on src/main/java/service/ServiceService.java
> +public class ServiceService {
Переименовал в ServiceDb

2017-10-19 13:28 UTC, sevaTechoPark commented on src/main/java/server/account/AccountService.java
> +            final String sql = "SELECT * FROM FUser "
Как в курсе БД... Убрал

2017-10-19 13:36 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +	private MockMvc mockMvc;
не понял

2017-10-19 14:01 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +        mockMvc.perform(post("/api/auth/signup")
json.put("username", getRandomString(SECURE_RANDOM, 10));
json.put("email", getRandomString(SECURE_RANDOM, 10));
json.put("password", getRandomString(SECURE_RANDOM, 10));
заменил везде на
createJsonResponse(json,null, null, null);

2017-10-19 14:20 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +package server.account.AccountControllerTest;
теперь 297 строк

2017-10-19 14:42 UTC, sevaTechoPark commented on src/main/java/server/account/AccountService.java
> +        } catch (DuplicateKeyException e) {
Сделано

2017-10-19 14:44 UTC, sevaTechoPark commented on src/main/java/server/account/AccountService.java
> +            return new ResponseEntity(account, HttpStatus.CREATED); // 201
почему? как тогда ошибки базы возвращать в контроллер?

2017-10-27 09:26 UTC, Badya requested changes

2017-10-27 09:26 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +    public void AccountDoesNotExistLogIn() throws Exception {
Naming convention

2017-10-27 09:26 UTC, Badya commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +package server.account.AccountControllerTest;
Можно еще отрефакторить

2017-10-27 09:26 UTC, Badya commented on src/test/java/server/account/AccountServiceTest/AccountServiceTest.java
> +    @Before
В каком порядке вызовутся `@Before` ?

2017-10-27 09:26 UTC, Badya commented on src/test/java/server/account/AccountServiceTest/AccountServiceTest.java
> +    public void createSimpleAccount() {
Что тут проверяется? что тут происходит?

2017-10-28 14:29 UTC, sevaTechoPark commented on src/test/java/server/account/AccountServiceTest/AccountServiceTest.java
> +    @Before
порядок вызова @Before в одном классе не гарантирован

2017-10-28 14:31 UTC, sevaTechoPark commented on src/test/java/server/account/AccountServiceTest/AccountServiceTest.java
> +    public void createSimpleAccount() {
Проверяется успешный сценарий. Чтобы было понимание, что сломалось самое базовое.

2017-10-28 14:31 UTC, sevaTechoPark commented on src/test/java/server/account/AccountControllerTest/AccountControllerTest.java
> +    public void AccountDoesNotExistLogIn() throws Exception {
с маленькой буквы должно быть. исправлю

2017-11-12 14:42 UTC, merged