RK3
java-park-mail-ru/CaesarTeam-09-2017 pull request #5
Opened 2017-11-18 16:01 UTC by sevaTechoPark

- [ ] init frontend
- [ ] movement to frontend
- [ ] bonus
- [ ] add custom timeFrame
- [ ] upgrade(less tiles, better architecture and other)
- [ ] multiplayer

2017-11-23 09:03 UTC, isopov commented
Начнём.
1. "You have 61 Checkstyle violations." - каким-то образом надо исправить (подавить, удалить эти инспекции из профиля, исправить, удалить нафиг весь чекстайл?)
2. maven-dependency-plugin & webapp-runner.jar - расскажите зачем вам это в приложении на spring-boot?
3. Тесты на игровую логику - нужны (хотя бы парочка на happy path)
4. `@After public void clearDatabaseAfter()` - тесты на базу должны быть транзакционными.
5. "public int x; // убрал final" - почему?
6. Если к классу Coords добавить геттеры, то в классе Config можно вместо 
```
Arrays.sort(bonusPosition, (obj1, obj2) -> {
            if (obj1.y > obj2.y) {
                return 1;
            } else if(obj1.y == obj2.y){

                if (obj1.x > obj2.x) {
                    return 1;
                } else if (obj1.x < obj2.x) {
                    return -1;
                }
                return 0;

            }
            return -1;
        });
```
Написать
```
Arrays.sort(bonusPosition, 
        		Comparator.comparing(Coords::getY)
            	.thenComparing(Coords::getX))
```
(И на это стоит написать тест, что вы не ошиблись в компараторе и он сортирует в правильную сторону!)
7. GameSessionService не выглядит потокобезопасным...

2017-11-23 09:04 UTC, isopov requested changes
Замечания в общих комментариях будут

2017-11-23 15:34 UTC, sevaTechoPark commented
1. Не знаю как побороть инспекцию на публичные переменные в классе. В слаке спросил, вы сказали использовать https://github.com/java-park-mail-ru/samples/commit/5aa7b7415db2622436317d588271f75a247a12c4 но он не говорит, где у меня ошибки, просто говорит что все плохо.
2. Я даже не знаю что это. Удалю.
3. Фронт еще не дописан. Как на нем заработает моя логика думал тесты запилить.
4. С аннотацией транзакшинал не работало в первом варианте. Попробую исправить.
5. Для того чтобы менять позицию игрока
6. Был уверен что такую банульную вещь в Java можно в пару строк обернуть, но не знал как, спасибо)
7. Пока только single делаю, после мультиплеер, а в чем у меня может проблема возникнуть?

2017-11-26 08:15 UTC, sevaTechoPark commented
- [ ] Должна быть выстроена архитектура транспорта сообщений клиент-сервер и сервер-клиент. Она должна быть расширяемой
- [ ] Должен быть проработан граф состояний игровой партии, в том числе процесс инициализации и действия в случае ошибок
- [ ] Должна быть понятна стратегия добавления недостающего контента и механик
- [ ] Должна быть реализована хотя бы одна механика, результаты действия которой можно увидеть на другом клиенте
- [ ] Должны быть написаны тесты на простейшие игровые сценарии. Например:
-2 игрока подключились, началась игровая партия.
-Началась игровая партия, первый игрок совершает простейшее действие и оно действительно совершается
-...

2017-11-29 14:58 UTC, isopov commented
1. utils.TestUtils.SECURE_RANDOM - а зачем вам криптографически стойкий рандом в тестах? И зачем там вам вообще рандом?
2. AccountDao - это скорее какой-нибудь DataSet, Entity - под DAO обычно всё-таки утилитный класс понимают.
3. В AccountDaoImpl
```
} finally {
            return accountDao;
        }
```
если выбрасывается какое-нибудь другое исключение, чем catch, то оно игнорируется и вместо его обработки/проброски делается return. Не делайте так никогда. (И это причина, почему транзакционные тесты не работают у вас - после вылета исключения внутри СУБД в транзакции в ней уже ничего нельзя делать - разбейте тесты на более мелкие, чтобы тестировать максимум по одному такому случаю в тесте)
4. AccountControllerTest.usernameOrEmailAlreadyExists() - зачем тут вообще два юзера пробовать? почему одного не хватает (ну и, получается, что у вас тесты на веб-слой и на дао-слой сильно дублируются)
5. `package technopark.model.account.AccountControllerTest;` - неожиданно)) - перенестие тесты в традиционное место - тот же пакет, что и тестируемый класс

ну и вообще этот РК про механику и систему сообщений с клиентом - и мне нужны тесты именно на них...

2017-12-08 16:38 UTC, sevaTechoPark commented
@isopov

2017-12-10 12:23 UTC, merged